---

- name: Install pre-reqs for ansible
  pip: name={{ item }}
    state=present
  with_items:
    - boto
    - PyYAML
    - Jinja2
    - httplib2
    - awscli

- name: install ansible
  pip: name=ansible
    state=present
