---

- name: Install pre-reqs for ansible (pip)
  sudo: true
  pip: name={{ item }}
    state=present
  with_items:
    - boto
    - awscli

- name: install ansible
  sudo: true
  pip: name=ansible
    state=present
